### ISSUE TITLE
static-glibc.sh failed to linking qbittorrent

### ISSUE THREAD

**Issue by Jylijs** [userdocs/qbittorrent-nox-static#3] opened 2020-04-03 04:42 UTC
I'm using Scaleway DEV1-L instances, OS: Debian 10

I run the following command:
```
wget https://github.com/userdocs/qbittorrent-nox-static/raw/master/qbittorrent-nox-static-glibc.sh -O a
time bash a all -nodel
```

And this is the reult:
```
linking qbittorrent-nox
/usr/bin/ld: /root/qbittorrent-build/lib/libQt5Core.a(qlibrary_unix.o): in function `qdlerror()':
qlibrary_unix.cpp:(.text._ZL8qdlerrorv+0xc): undefined reference to `dlerror'
/usr/bin/ld: /root/qbittorrent-build/lib/libQt5Core.a(qlibrary_unix.o): in function `QLibraryPrivate::unload_sys()':
qlibrary_unix.cpp:(.text._ZN15QLibraryPrivate10unload_sysEv+0x13): undefined reference to `dlclose'
/usr/bin/ld: /root/qbittorrent-build/lib/libQt5Core.a(qlibrary_unix.o): in function `QLibraryPrivate::resolve_sys(char const*)':
qlibrary_unix.cpp:(.text._ZN15QLibraryPrivate11resolve_sysEPKc+0x5): undefined reference to `dlsym'
/usr/bin/ld: /root/qbittorrent-build/lib/libQt5Core.a(qlibrary_unix.o): in function `QLibraryPrivate::load_sys()':
qlibrary_unix.cpp:(.text._ZN15QLibraryPrivate8load_sysEv+0x608): undefined reference to `dlopen'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:594: qbittorrent-nox] Error 1
make[1]: Leaving directory '/root/qbittorrent-build/qbittorrent/src'
make: *** [Makefile:47: sub-src-make_first] Error 2
```

**Comment by userdocs** [comment] 2020-04-03 09:19
I saw this when making some changes https://github.com/userdocs/qbittorrent-nox-static/commit/9e0656524441042555d1bb3ff298af242f624b76 . I am unsure what changed as it appears platform related rather than script.

It is definitely related to the use of `--static -static` as this build script works fine without those.

I am still looking into the cause of this one. Any input is welcome.

**Comment by userdocs** [comment] 2020-04-03 13:49
fixed with this commit https://github.com/userdocs/qbittorrent-nox-static/commit/e20f6c0179fde94cea85938824e1605db33b3f4a

new qbittorrent 4.2.3 builds added as a result.

Please test and confirm.

**Comment by Jylijs** [comment] 2020-04-05 01:24
Thanks, both your build and the build script works.

**Closed** 2020-04-05 05:20 UTC
