### ISSUE TITLE
Error in Termux

### ISSUE THREAD

**Issue by cheungchingli** [userdocs/qbittorrent-nox-static#79] opened 2022-03-13 10:59 UTC
no ```/etc/resolv.conf``` and the wrong timezone

**Comment by userdocs** [comment] 2022-04-27 13:55
Not sure what to do here. IF oyu can provide more info as to the problem i can take a look and reopen the issue. For now i will close it as i am not sure what the problem is.

**Closed by userdocs** 2022-04-27 13:55 UTC
